[project]
name = "okpedafe"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "imagehash>=4.3.2",
    "panel>=1.8.7",
    "pillow>=12.1.0",
    "plotly>=6.5.2",
]
